# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more :
# https://aka.ms/yaml

trigger:
- main

pool: VMSS-POC

steps:
  - task: Bash@3
    displayName: 'Step 1: Print Tools Directory'
    inputs:
      targetType: 'inline'
      script: |
        # Print the path to the tools directory
        echo "Agent.ToolsDirectory (1): $(Agent.ToolsDirectory)"


  - task: Bash@3
    displayName: 'Step 2: Override Tools Directory'
    inputs:
      targetType: 'inline'
      script: |

        echo "Overridden Agent Tools Directory AGENT_TOOLSDIRECTORY: $AGENT_TOOLSDIRECTORY"
        echo "Agent Tools Directory Agent.ToolsDirectory: $(Agent.ToolsDirectory)"
  
  - task: Bash@3
    displayName: 'Step 3: Navigate to /agent/_work/_tool and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /agent/_work/_tool

        # List the contents of the directory
        ls
        pwd
        
  - task: Bash@3
    displayName: 'Step 4: View Permissions of the Folder and File'
    inputs:
      targetType: 'inline'
      script: |
        # View permissions of the directory
        ls -la /sagnew11/node/14.21.3/x64/

        # View permissions of the specific file
        ls -la /sagnew11/node/14.21.3/x64/CHANGELOG.md      

  - task: NodeTool@0
    displayName: 'Step 4.1: Install Node.js'
    inputs:
      versionSpec: '14.x'
      
  # - task: Bash@3
  #   displayName: 'Step 4: Install Node.js'
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       sudo apt-get update
  #       sudo apt-get install -yq build-essential  # Install build-essential (includes make)
  #       export NPM_CONFIG_PREFIX=$(Agent.ToolsDirectory)/node14
  #       curl -L https://git.io/n-install | bash -s -- -n -q
    
  - task: Bash@3
    displayName: 'Step 5: Navigate to /agent/_work/_tool and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /agent/_work/_tool

        # List the contents of the directory
        ls      
        pwd

  - task: Bash@3
    displayName: 'Step 6: Navigate to /sagnew11 and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /sagnew11

        # List the contents of the directory
        ls      
        pwd

  - task: Bash@3
    displayName: 'Step 6: View Directory Permissions'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /agent/_work/_tool

        # List directory contents with detailed information including permissions
        ls -la        

  - task: Bash@3
    displayName: 'Step 7: List Permissions of the Directory'
    inputs:
      targetType: 'inline'
      script: |
        ls -la /sagnew11/node/14.21.3/x64/     




