# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: VMSS-POC

steps:
  - task: Bash@3
    displayName: 'Step 1: Print Tools Directory'
    inputs:
      targetType: 'inline'
      script: |
        # Print the path to the tools directory
        echo "Agent.ToolsDirectory (1): $(Agent.ToolsDirectory)"


  - task: Bash@3
    displayName: 'Step 2: Override Tools Directory'
    inputs:
      targetType: 'inline'
      script: |

        echo "Overridden Agent Tools Directory AGENT_TOOLSDIRECTORY: $AGENT_TOOLSDIRECTORY"
        echo "Agent Tools Directory Agent.ToolsDirectory: $(Agent.ToolsDirectory)"
  
  - task: Bash@3
    displayName: 'Step 3: Navigate to /agent/_work/_tool and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /agent/_work/_tool

        # List the contents of the directory
        ls
        pwd
        
  # - task: NodeTool@0
  #   displayName: 'Step 4: Install Node.js'
  #   inputs:
  #     versionSpec: '14.x'
      
  - task: Bash@3
    displayName: 'Step 4: Install Node.js'
    inputs:
      targetType: 'inline'
      script: |
        export NPM_CONFIG_PREFIX=$(Agent_ToolsDirectory)/node14
        curl -L https://git.io/n-install | bash
        source ~/.bashrc
        n 14.x
    
  - task: Bash@3
    displayName: 'Step 5: Navigate to /agent/_work/_tool and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /agent/_work/_tool

        # List the contents of the directory
        ls      
        pwd

  - task: Bash@3
    displayName: 'Step 6: Navigate to /sagnew11 and do ls'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /sagnew11

        # List the contents of the directory
        ls      
        pwd

  - task: Bash@3
    displayName: 'Step 6: View Directory Permissions'
    inputs:
      targetType: 'inline'
      script: |
        # Navigate to the specified path
        cd /agent/_work/_tool

        # List directory contents with detailed information including permissions
        ls -la        

  - task: Bash@3
    displayName: 'Step 7: List Permissions of the Directory'
    inputs:
      targetType: 'inline'
      script: |
        ls -la /sagnew11/node/14.21.3/x64/     

  - task: Bash@3
    displayName: 'Step 8: Modify Permissions of the Directory'
    inputs:
      targetType: 'inline'
      script: |
        chmod -R 755 /sagnew11/node/14.21.3/x64/ 



